version: 0.2

phases:
  pre-build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
